### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Ravikumawat1990** [vkpdeveloper/flutterpaytm#2]
D/AppSignatureHelper(31537): pkg: com.example.upipayment -- hash: 0y7e3DJBAOq
I/flutter (31537): 0y7e3DJBAOq
E/MethodChannel#flutterpaytm(31537): Failed to handle method call
E/MethodChannel#flutterpaytm(31537): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
E/MethodChannel#flutterpaytm(31537): 	at tk.vkpdeveloper.flutterpaytm.FlutterpaytmPlugin.onMethodCall(FlutterpaytmPlugin.java:38)
E/MethodChannel#flutterpaytm(31537): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#flutterpaytm(31537): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutterpaytm(31537): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#flutterpaytm(31537): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutterpaytm(31537): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#flutterpaytm(31537): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#flutterpaytm(31537): 	at android.app.ActivityThread.main(ActivityThread.java:7682)
E/MethodChannel#flutterpaytm(31537): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutterpaytm(31537): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/MethodChannel#flutterpaytm(31537): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by vkpdeveloper** [comment]
give whole init payment code.
